"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, Download, ExternalLink, Plus, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { EvidenceViewer } from "./EvidenceViewer";
import { approvedCopy, findArtifact, topicMedia, projectDemo, projects, spiralExplorations, type RichBlock } from "@/lib/data/portfolio-rebuild";

function RichText({ blocks }: { blocks: readonly RichBlock[] }) { return <>{blocks.map((block) => <p key={block.id}>{block.kind === "emphasis" ? <strong>{block.text}</strong> : block.text}</p>)}</>; }
function MediaStage({ id, inspect, priority = false }: { id: string; inspect: (id: string) => void; priority?: boolean }) {
  const artifact = findArtifact(id), media = artifact?.media;
  if (!media) return null;
  if (media.publication !== "approved" || !media.assetPath || !media.width || !media.height) return <div className="media-slot media-slot--portrait media-pending"><div className="media-slot__screen"><span className="eyebrow">POCKET SPIRAL</span><p>{media.caption}</p><small>A reviewed physical-device screenshot is on its way.</small></div></div>;
  return <figure className={"media-figure media-figure--" + media.orientation}><button type="button" className="media-capture" onClick={() => inspect(id)} aria-label={"Inspect " + media.title}><Image src={media.assetPath} alt={media.alt} width={media.width} height={media.height} priority={priority} sizes={media.orientation === "portrait" ? "(max-width:600px) 80vw,330px" : "(max-width:900px) 90vw,70vw"}/></button><figcaption>{media.caption}</figcaption></figure>;
}
function MediaControls({ project, topic, inspect }: { project: string; topic: string; inspect: (id: string) => void }) { return <div className="media-controls">{topicMedia(project, topic).map(a => <button key={a.id} type="button" className="evidence-link" onClick={() => inspect(a.id)}>{a.media!.controlLabel}</button>)}</div>; }


export function PortfolioExperience() {
  const [spiral, setSpiral] = useState<string | null>(null), [hoveredLayer, setHoveredLayer] = useState<string | null>(null), [openProject, setOpenProject] = useState<Record<string,string|undefined>>({}), [evidence, setEvidence] = useState<string | null>(null);
  const restoredRef = useRef(false), evidenceRef = useRef(evidence); evidenceRef.current = evidence;
  const triggerRef = useRef<HTMLButtonElement | null>(null), closeRef = useRef<HTMLButtonElement | null>(null), inspectionRef = useRef<HTMLElement | null>(null);
  const node = spiralExplorations.find((item) => item.id === spiral), active = (id:string) => hoveredLayer === id || spiral === id;
  useEffect(() => { const restore = () => { const p = new URLSearchParams(window.location.search), expanded = Object.fromEntries((p.get("explore") ?? "").split(",").map(entry=>entry.split(":")).filter(([project,panel])=>projects.some(item=>item.slug===project && item.explorations.some(x=>x.id===panel)))); setSpiral(spiralExplorations.some((item)=>item.id===p.get("spiral")) ? p.get("spiral") : null); setEvidence(findArtifact(p.get("evidence") ?? "") ? p.get("evidence") : null); setOpenProject(expanded); restoredRef.current = false; }; restore(); window.addEventListener("popstate",restore); return ()=>window.removeEventListener("popstate",restore); }, []);
  useEffect(() => { if (!restoredRef.current) { restoredRef.current = true; return; } const url = new URL(window.location.href), open = Object.entries(openProject).filter(([,panel])=>panel).map(entry=>entry.join(":")).join(","); spiral?url.searchParams.set("spiral",spiral):url.searchParams.delete("spiral"); evidence?url.searchParams.set("evidence",evidence):url.searchParams.delete("evidence"); open?url.searchParams.set("explore",open):url.searchParams.delete("explore"); const next=`${url.pathname}${url.search}${url.hash}`; if(next!==`${window.location.pathname}${window.location.search}${window.location.hash}`) window.history.pushState({},"",next); }, [spiral,evidence,openProject]);
  useEffect(() => { if(!spiral) return; if(inspectionRef.current) inspectionRef.current.scrollTop=0; closeRef.current?.focus(); const escape=(event:KeyboardEvent)=>{if(event.key==="Escape" && !evidenceRef.current && !event.defaultPrevented){setSpiral(null);triggerRef.current?.focus()}}; window.addEventListener("keydown",escape); return()=>window.removeEventListener("keydown",escape); }, [spiral]);
  const openLayer=(id:string, trigger?:HTMLButtonElement)=>{triggerRef.current=trigger??(document.activeElement instanceof HTMLButtonElement?document.activeElement:null); setSpiral(id)}, closeLayer=()=>{setSpiral(null);triggerRef.current?.focus()};
  const interaction = (id:string, trigger?:HTMLButtonElement) => ({ onMouseEnter:()=>setHoveredLayer(id), onMouseLeave:()=>setHoveredLayer(null), onFocus:()=>setHoveredLayer(id), onBlur:()=>setHoveredLayer(null), onClick:()=>openLayer(id,trigger) });

  return <main>
    <section className="hero"><div className="shell hero__grid"><div className="hero__copy"><p className="eyebrow">KAREEM SINGLETON · PHILADELPHIA, PA</p><h1>{approvedCopy.hero[0].text}</h1><p className="hero__body">{approvedCopy.hero[1].text}</p><p className="identity">Kareem Singleton<br/><span>AI Systems Architect · Product Builder · Founder, Capsule Foundry</span></p><div className="actions"><a className="button button--gold" href="#spiral">Explore my work <ArrowDown/></a><a className="button button--quiet" href="#contact">Work with me <ArrowUpRight/></a><a className="text-link" href="/resume/Kareem_Singleton_Resume_2026.pdf" target="_blank">View résumé <Download/></a></div></div><div className="hero__stage"><MediaStage id="s1-c01" inspect={setEvidence} priority/></div></div></section>
    <section id="about" className="section section--about"><div className="shell about"><div className="about__image"><Image src="/images/kareem-singleton.jpg" alt="Kareem Singleton" width={1170} height={1532} sizes="(min-width:900px) 36vw,80vw" priority/></div><div className="about__copy"><p className="eyebrow">ABOUT</p><h2>I built my way in.</h2><RichText blocks={approvedCopy.about}/><a href="#spiral" className="text-link">Meet Spiral One <ArrowDown/></a></div></div></section>
    <section id="spiral" className="section spiral"><div className="shell"><div className="spiral__intro"><p className="eyebrow">THE SYSTEM BEHIND THE SYSTEMS</p><h2>The system I built to build systems.</h2><div className="prose"><RichText blocks={approvedCopy.spiralIntro}/></div></div><div className="spiral-stage"><MediaStage id="s1-workspace" inspect={setEvidence}/></div>
      <div className={`spiral-architecture ${spiral?"is-inspecting":""}`}><div className="architecture-art"><Image src="/images/spiral-one-architecture.png" alt="Seven holographic system layers connected by a luminous vertical beam and golden helix" width={1024} height={1536} sizes="(min-width:900px) 48vw,100vw" priority/><div className="architecture-art__regions">{spiralExplorations.map((item,index)=><button key={item.id} type="button" className={`architecture-disc architecture-disc--${index+1} ${active(item.id)?"is-active":""}`} aria-label={`Explore ${item.label}`} aria-pressed={spiral===item.id} {...interaction(item.id)}/>)}</div><div className="architecture-annotations" aria-label="Spiral One layer labels">{spiralExplorations.map((item,index)=><button key={item.id} type="button" className={`architecture-annotation architecture-annotation--${index+1} ${active(item.id)?"is-active":""}`} {...interaction(item.id)}><span>{String(index+1).padStart(2,"0")}</span><strong>{item.label}</strong></button>)}</div></div><div className="architecture-explorer"><div className="architecture-copy"><p className="eyebrow">SPIRAL ONE ARCHITECTURE</p><h3>Choose a system layer to explore how it carries the work.</h3><p>Each layer has a specific job. Together they carry context into working software, verify what it built, learn from it, and recover when things go wrong.</p></div><div className="architecture-map" aria-label="Spiral One architecture navigator">{spiralExplorations.map((item,index)=><button key={item.id} type="button" className={`architecture-node ${active(item.id)?"is-selected":""}`} aria-pressed={spiral===item.id} {...interaction(item.id)} onClick={(event)=>openLayer(item.id,event.currentTarget)}><span>{String(index+1).padStart(2,"0")}</span><strong>{item.label}</strong><small>{item.navSummary}</small><ArrowUpRight/></button>)}</div></div>{node&&<aside ref={inspectionRef} className="architecture-inspection" aria-live="polite" aria-labelledby="architecture-inspection-title"><header><p className="eyebrow">{String(spiralExplorations.findIndex((item)=>item.id===node.id)+1).padStart(2,"0")} · {node.label}</p><button ref={closeRef} className="icon-button" type="button" onClick={closeLayer} aria-label="Close Spiral One detail"><X/></button></header><h3 id="architecture-inspection-title">{node.heading}</h3>{node.copy.map((paragraph)=><p key={paragraph}>{paragraph}</p>)}<div className="inspection-outline"><p>ON THIS PAGE</p><span>How it works</span><span>Key components</span><span>Technical details</span></div><MediaControls project="spiral-one" topic={node.id} inspect={setEvidence}/><div className="panel-actions"><Link className="button button--gold" href={node.technical}>Go deeper <ArrowUpRight/></Link><button type="button" className="evidence-link" onClick={()=>setEvidence(node.artifact)}>Inspect evidence</button></div></aside>}</div>
    </div></section>
    <section className="section loop"><div className="shell"><p className="eyebrow">THE LOOP</p><h2>I want the build to teach the builder.</h2><div className="loop__line"><span>Council</span><i/><span>Build</span><i/><span>Verification</span><i/><span>FHRA</span><i/><span>Knowledge</span><i/><span>Next build</span></div><p className="loop__body">Council can expose something we didn&apos;t consider. The build tests the idea against reality. Verification checks what actually happened. FHRA steps back and looks at the whole thing. The Empirical Knowledge Ledger keeps what was worth learning.</p><p className="loop__statement">The next problem shouldn&apos;t always start from zero.</p><Link href="/work/spiral-one" className="text-link">Go deeper into Spiral One <ArrowUpRight/></Link></div></section>
    <section id="work" className="section built"><div className="shell"><div className="built__heading"><p className="eyebrow">BUILT THROUGH SPIRAL ONE</p><h2>The proof is in what it builds.</h2><RichText blocks={approvedCopy.builtThrough}/></div>{projects.filter((project)=>project.slug!=="spiral-one").map((project,index)=>{const openId=openProject[project.slug], exploration=project.explorations.find((item)=>item.id===openId);return <article key={project.slug} className={`project project--${project.slug}`} id={project.slug}><div className="project__media"><MediaStage id={project.media[0].id} inspect={setEvidence}/>{projectDemo(project.slug)&&<button type="button" className="evidence-link watch-demo" onClick={()=>setEvidence(projectDemo(project.slug)!.id)}>Watch demo <ArrowUpRight/></button>}</div><div className="project__content"><p className="eyebrow">0{index+1} · {project.eyebrow}</p><h2>{project.thesis}</h2>{project.copy.map((paragraph)=><p key={paragraph}>{paragraph}</p>)}<p className="technologies">{project.technologies.join(" · ")}</p><div className="explore-list">{project.explorations.map((item)=><button type="button" key={item.id} className={openId===item.id?"is-open":""} onClick={()=>setOpenProject((state)=>({...state,[project.slug]:state[project.slug]===item.id?undefined:item.id}))}>{item.label}<Plus/></button>)}</div>{exploration&&<div className="project-explore"><p className="eyebrow">{exploration.label}</p><h3>{exploration.heading}</h3>{exploration.copy.map((paragraph)=><p key={paragraph}>{paragraph}</p>)}<MediaControls project={project.slug} topic={exploration.id} inspect={setEvidence}/><div className="panel-actions"><Link className="text-link" href={exploration.technical}>Technical details <ArrowUpRight/></Link><button type="button" className="evidence-link" onClick={()=>setEvidence(exploration.artifact)}>Inspect evidence</button></div></div>}<Link href={`/work/${project.slug}`} className="project-deep-link">Open the hood <ArrowUpRight/></Link></div></article>})}</div></section>
    <section className="section thesis"><div className="shell thesis__inner"><p className="eyebrow">DIFFERENT PROBLEMS. SAME INSTINCT.</p><h2>What can the system handle so the person can spend their intelligence on what actually needs them?</h2><p>That&apos;s the kind of software I want to build.</p></div></section><section className="section closing"><div className="shell"><p className="eyebrow">A NOTE TO THE BUILDER</p><h2>Let the dreamers keep dreaming.</h2><div className="closing__copy"><RichText blocks={approvedCopy.closing}/></div></div></section><section id="contact" className="contact"><div className="shell contact__inner"><div><p className="eyebrow">WORK WITH ME</p><h2>Let&apos;s build around the idea.</h2></div><div className="actions"><a className="button button--gold" href="https://calendly.com/capsulefoundry/ai-automation-discovery-call" target="_blank">Work with me <ExternalLink/></a><a className="button button--quiet" href="/resume/Kareem_Singleton_Resume_2026.pdf" target="_blank">View résumé <Download/></a></div></div></section>
    <EvidenceViewer artifact={findArtifact(evidence??"")} onClose={()=>setEvidence(null)}/>
  </main>;
}
